export const defaultProgamState = {
  winamp: {
    id: "wp",
    name: "Winamp",
    isOpen: false,
    isFocused: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 0,
  },
  intExplorer: {
    id: "ie",
    name: "Internet Explorer",
    isOpen: false,
    isFocused: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 0,
  },
  msn: {
    id: "msn",
    name: "Messenger",
    isOpen: true,
    isFocused: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 0,
  },
  paint: {
    id: "paint",
    name: "Paint",
    isOpen: false,
    isFocused: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 0,
  },
  projects: {
    id: "projects",
    name: "Projects",
    isOpen: false,
    isFocused: false,
    isMinimized: false,
    isMaximized: false,
    zIndex: 0,
  },
};
